### ISSUE TITLE
What's masks.pt file in the code?

### ISSUE THREAD

**Issue by hzjsxu** [ruocheny/SCCN-LoG#1]
Hi，wonderful work! Here I have a problem: can you provide the masks.pt file or tell how to generate this file?  
---------------------------------------------------------------------------------
![image](https://github.com/ruocheny/SCCN-LoG/assets/45815139/1b336fb1-224c-4d8a-96fd-0501818b4ce3)

**Comment by ruocheny** [comment]
Thanks for checking our code! To generate mask, you can just simply add `--genmask` such as
`python train.py --dataname cora --pseudospx --modelname scn --earlystp --genmasks`.

**Comment by hzjsxu** [comment]
> Thanks for checking our code! To generate mask, you can just simply add `--genmask` such as `python train.py --dataname cora --pseudospx --modelname scn --earlystp --genmasks`.

I got it. Thanks for your reply.
